area/src:
- changed-files:
  - any-glob-to-any-file:
    - "src/**/*"
area/cli:
- changed-files:
  - any-glob-to-any-file:
    - "bin/**/*"
area/test:
- changed-files:
  - any-glob-to-any-file:
    - "test/**/*"
area/docs:
- changed-files:
  - any-glob-to-any-file:
    - "docs/**/*"
area/ci:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"